name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Product Docker image
        run: docker build -t product-service ./product-service

      - name: Build Order Docker image
        run: docker build -t order-service ./order-service

      - name: Check Product Service
        run: python -m py_compile product-service/app.py

      - name: Check Order Service
        run: python -m py_compile order-service/app.py
